//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace ValhallaLootList.Server.Migrations
{
    public partial class AddVerifiedByToChar : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "IsLeader",
                table: "Characters");

            migrationBuilder.AlterColumn<long>(
                name: "OwnerId",
                table: "Characters",
                type: "bigint",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "longtext CHARACTER SET utf8mb4",
                oldNullable: true);

            migrationBuilder.AddColumn<long>(
                name: "VerifiedById",
                table: "Characters",
                type: "bigint",
                nullable: true);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "VerifiedById",
                table: "Characters");

            migrationBuilder.AlterColumn<string>(
                name: "OwnerId",
                table: "Characters",
                type: "longtext CHARACTER SET utf8mb4",
                nullable: true,
                oldClrType: typeof(long),
                oldType: "bigint",
                oldNullable: true);

            migrationBuilder.AddColumn<bool>(
                name: "IsLeader",
                table: "Characters",
                type: "tinyint(1)",
                nullable: false,
                defaultValue: false);
        }
    }
}
