//<auto-generated>
using System;
using Microsoft.EntityFrameworkCore.Migrations;

namespace ValhallaLootList.Server.Migrations
{
    public partial class AddBracketsToDb : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Brackets",
                columns: table => new
                {
                    Phase = table.Column<byte>(type: "tinyint unsigned", nullable: false),
                    Index = table.Column<byte>(type: "tinyint unsigned", nullable: false),
                    MinRank = table.Column<byte>(type: "tinyint unsigned", nullable: false),
                    MaxRank = table.Column<byte>(type: "tinyint unsigned", nullable: false),
                    MaxItems = table.Column<byte>(type: "tinyint unsigned", nullable: false),
                    AllowOffspec = table.Column<bool>(type: "tinyint(1)", nullable: false),
                    AllowTypeDuplicates = table.Column<bool>(type: "tinyint(1)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Brackets", x => new { x.Phase, x.Index });
                });

            migrationBuilder.CreateTable(
                name: "PhaseDetails",
                columns: table => new
                {
                    Id = table.Column<byte>(type: "tinyint unsigned", nullable: false),
                    StartsAtUtc = table.Column<DateTime>(type: "datetime(6)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PhaseDetails", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "Brackets",
                columns: new[] { "Index", "Phase", "AllowOffspec", "AllowTypeDuplicates", "MaxItems", "MaxRank", "MinRank" },
                values: new object[,]
                {
                    { (byte)0, (byte)1, false, false, (byte)1, (byte)18, (byte)15 },
                    { (byte)1, (byte)1, false, false, (byte)1, (byte)14, (byte)11 },
                    { (byte)2, (byte)1, false, false, (byte)2, (byte)10, (byte)7 },
                    { (byte)3, (byte)1, true, true, (byte)2, (byte)6, (byte)1 }
                });

            migrationBuilder.InsertData(
                table: "PhaseDetails",
                columns: new[] { "Id", "StartsAtUtc" },
                values: new object[] { (byte)1, new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified) });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Brackets");

            migrationBuilder.DropTable(
                name: "PhaseDetails");
        }
    }
}
