//<auto-generated>
using Microsoft.EntityFrameworkCore.Migrations;

namespace ValhallaLootList.Server.Migrations
{
    public partial class ChangeRaidToPhases : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_Raids_Instances_InstanceId",
                table: "Raids");

            migrationBuilder.DropIndex(
                name: "IX_Raids_InstanceId",
                table: "Raids");

            migrationBuilder.DropColumn(
                name: "InstanceId",
                table: "Raids");

            migrationBuilder.DropColumn(
                name: "UsingOffspec",
                table: "RaidAttendees");

            migrationBuilder.AddColumn<byte>(
                name: "Phase",
                table: "Raids",
                type: "tinyint unsigned",
                nullable: false,
                defaultValue: (byte)0);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "Phase",
                table: "Raids");

            migrationBuilder.AddColumn<string>(
                name: "InstanceId",
                table: "Raids",
                type: "varchar(255) CHARACTER SET utf8mb4",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<bool>(
                name: "UsingOffspec",
                table: "RaidAttendees",
                type: "tinyint(1)",
                nullable: false,
                defaultValue: false);

            migrationBuilder.CreateIndex(
                name: "IX_Raids_InstanceId",
                table: "Raids",
                column: "InstanceId");

            migrationBuilder.AddForeignKey(
                name: "FK_Raids_Instances_InstanceId",
                table: "Raids",
                column: "InstanceId",
                principalTable: "Instances",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
