//<auto-generated />
using Microsoft.EntityFrameworkCore.Migrations;

namespace ValhallaLootList.Server.Migrations
{
    public partial class RedoDropRelationships : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_DropPasses_Drops_DropEncounterKillRaidId_DropEncounterKillEn~",
                table: "DropPasses");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Drops",
                table: "Drops");

            migrationBuilder.DropPrimaryKey(
                name: "PK_DropPasses",
                table: "DropPasses");

            migrationBuilder.DropColumn(
                name: "PassCount",
                table: "LootListEntries");

            migrationBuilder.DropColumn(
                name: "Won",
                table: "LootListEntries");

            migrationBuilder.DropColumn(
                name: "DropEncounterKillRaidId",
                table: "DropPasses");

            migrationBuilder.DropColumn(
                name: "DropItemId",
                table: "DropPasses");

            migrationBuilder.RenameColumn(
                name: "DropEncounterKillEncounterId",
                table: "DropPasses",
                newName: "DropId");

            migrationBuilder.AddColumn<string>(
                name: "DropId",
                table: "LootListEntries",
                type: "varchar(255) CHARACTER SET utf8mb4",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "Id",
                table: "Drops",
                type: "varchar(255) CHARACTER SET utf8mb4",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AlterColumn<string>(
                name: "OwnerId",
                table: "Characters",
                type: "longtext CHARACTER SET utf8mb4",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "longtext CHARACTER SET utf8mb4");

            migrationBuilder.AddPrimaryKey(
                name: "PK_Drops",
                table: "Drops",
                column: "Id");

            migrationBuilder.AddPrimaryKey(
                name: "PK_DropPasses",
                table: "DropPasses",
                columns: new[] { "DropId", "CharacterId" });

            migrationBuilder.CreateIndex(
                name: "IX_LootListEntries_DropId",
                table: "LootListEntries",
                column: "DropId",
                unique: true);

            migrationBuilder.AddForeignKey(
                name: "FK_DropPasses_Drops_DropId",
                table: "DropPasses",
                column: "DropId",
                principalTable: "Drops",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_LootListEntries_Drops_DropId",
                table: "LootListEntries",
                column: "DropId",
                principalTable: "Drops",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_DropPasses_Drops_DropId",
                table: "DropPasses");

            migrationBuilder.DropForeignKey(
                name: "FK_LootListEntries_Drops_DropId",
                table: "LootListEntries");

            migrationBuilder.DropIndex(
                name: "IX_LootListEntries_DropId",
                table: "LootListEntries");

            migrationBuilder.DropPrimaryKey(
                name: "PK_Drops",
                table: "Drops");

            migrationBuilder.DropPrimaryKey(
                name: "PK_DropPasses",
                table: "DropPasses");

            migrationBuilder.DropColumn(
                name: "DropId",
                table: "LootListEntries");

            migrationBuilder.DropColumn(
                name: "Id",
                table: "Drops");

            migrationBuilder.RenameColumn(
                name: "DropId",
                table: "DropPasses",
                newName: "DropEncounterKillEncounterId");

            migrationBuilder.AddColumn<short>(
                name: "PassCount",
                table: "LootListEntries",
                type: "smallint",
                nullable: false,
                defaultValue: (short)0);

            migrationBuilder.AddColumn<bool>(
                name: "Won",
                table: "LootListEntries",
                type: "tinyint(1)",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "DropEncounterKillRaidId",
                table: "DropPasses",
                type: "varchar(255) CHARACTER SET utf8mb4",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<uint>(
                name: "DropItemId",
                table: "DropPasses",
                type: "int unsigned",
                nullable: false,
                defaultValue: 0u);

            migrationBuilder.AlterColumn<string>(
                name: "OwnerId",
                table: "Characters",
                type: "longtext CHARACTER SET utf8mb4",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "longtext CHARACTER SET utf8mb4",
                oldNullable: true);

            migrationBuilder.AddPrimaryKey(
                name: "PK_Drops",
                table: "Drops",
                columns: new[] { "EncounterKillRaidId", "EncounterKillEncounterId", "ItemId" });

            migrationBuilder.AddPrimaryKey(
                name: "PK_DropPasses",
                table: "DropPasses",
                columns: new[] { "DropEncounterKillRaidId", "DropEncounterKillEncounterId", "DropItemId", "CharacterId" });

            migrationBuilder.AddForeignKey(
                name: "FK_DropPasses_Drops_DropEncounterKillRaidId_DropEncounterKillEn~",
                table: "DropPasses",
                columns: new[] { "DropEncounterKillRaidId", "DropEncounterKillEncounterId", "DropItemId" },
                principalTable: "Drops",
                principalColumns: new[] { "EncounterKillRaidId", "EncounterKillEncounterId", "ItemId" },
                onDelete: ReferentialAction.Cascade);
        }
    }
}
