// Copyright (C) 2021 Donovan Sullivan
// GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
// <auto-generated />

using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ValhallaLootList.Server.Migrations;

public partial class UpdateP1Brackets : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.UpdateData(
            table: "Brackets",
            keyColumns: new[] { "Index", "Phase" },
            keyValues: new object[] { (byte)1, (byte)1 },
            column: "NormalItems",
            value: (byte)2);

        migrationBuilder.UpdateData(
            table: "Brackets",
            keyColumns: new[] { "Index", "Phase" },
            keyValues: new object[] { (byte)2, (byte)1 },
            column: "NormalItems",
            value: (byte)2);

        migrationBuilder.UpdateData(
            table: "Brackets",
            keyColumns: new[] { "Index", "Phase" },
            keyValues: new object[] { (byte)3, (byte)1 },
            column: "NormalItems",
            value: (byte)2);
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.UpdateData(
            table: "Brackets",
            keyColumns: new[] { "Index", "Phase" },
            keyValues: new object[] { (byte)1, (byte)1 },
            column: "NormalItems",
            value: (byte)1);

        migrationBuilder.UpdateData(
            table: "Brackets",
            keyColumns: new[] { "Index", "Phase" },
            keyValues: new object[] { (byte)2, (byte)1 },
            column: "NormalItems",
            value: (byte)1);

        migrationBuilder.UpdateData(
            table: "Brackets",
            keyColumns: new[] { "Index", "Phase" },
            keyValues: new object[] { (byte)3, (byte)1 },
            column: "NormalItems",
            value: (byte)1);
    }
}
