name: Build and Deploy Dev
on:
  push:
    branches:
    - master
env:
  AZURE_WEBAPP_NAME: ValhallaLootList-linux-dev
  AZURE_WEBAPP_PACKAGE_PATH: src/Server/published
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.ValhallaLootList_linux_dev_fa16 }}
  ConnectionStrings:DefaultConnection: ${{ secrets.DEVCONNECTION }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 7.0.2xx
  WORKING_DIRECTORY: src/Server
  MIGRATE_DIRECTORY: src/SeedAndMigrate
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test --no-build
    - name: Seed and Migrate
      run: dotnet run --project "${{ env.MIGRATE_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore --no-build
    - name: Publish
      run: dotnet publish "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ env.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
